language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

install:
  - composer selfupdate
  - composer install

before_script:
  - mysql -e 'create database `test`;'
  - mysql --default-character-set=utf8 test < test/test.sql
