language: php

php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: 7

install:
  - composer self-update
  - composer install

before_script:
  - mysql -e 'create database `test`;'
  - mysql --default-character-set=utf8 test < test/test.sql
